name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - master
      - main
  merge_group:

jobs:
  build:
    name: Build
    runs-on: hanzo-build-linux-amd64
    steps:
      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod

      - name: Build
        run: go build .

      - name: Test
        run: go test -v -race -count=1 -timeout=5m -coverprofile=coverage.out ./...
